#############################################################################
# Skirnir                                                                   #
#############################################################################




#####	db_script_string	#####

SET NAMES 'utf8';
UPDATE `db_script_string` SET `content_loc3` = NULL;

UPDATE db_script_string SET content_loc3 = 'Seit die Sperber so einen großen Erfolg bei der Jagd nach den Rabensteine verbucht haben, hat Behüterin Elaira einen Weiteren trainiert, um meine Stimme über eine große Distanz zu übertragen. Er kann uns helfen miteinander zu kommunizieren während ihr den Vogelgeist der in der Schreibtafel gefangen ist erkundet!' WHERE ( entry = 2000000000);
UPDATE db_script_string SET content_loc3 = 'Die Schreibtafel gibt uns die Bestätigung, die wir benötigen, genau wie ich dachte. jetzt müssen wir diese Informationen gebrauchen, um auszuziehen und Anzu zu besiegen bevor er dem smaragdgrünen Traum noch mehr Schaden zufügen kann!' WHERE ( entry = 2000000001);
UPDATE db_script_string SET content_loc3 = 'Hier ist sogar noch etwas. Nach der Beschreibung eines blutigen Krieges und dem Untergang der Raben ist hier eine Prophezeiung. Anzu wird seine Feinde in deren Träumen heimsuchen und sie dazu überreden ihm die Rückkehr in diese Welt zu ermöglichen...' WHERE ( entry = 2000000002);
UPDATE db_script_string SET content_loc3 = 'Es ist alles hier... wie die Verfolger der Raben die Sprinter der Rivalen gefangen und unterworfen haben und sie für immer in Steinstatuen gefangen genommen haben! Die Schreibtafel erwähnt sogar den Namen des Rabengottes -- Anzu. Ich hätte gedacht dieser wäre im Laufe der Zeit verloren gegangen!' WHERE ( entry = 2000000003);
UPDATE db_script_string SET content_loc3 = 'Das ist es! Das ist es wirklich -- Das Buch des Raben!' WHERE ( entry = 2000000004);
UPDATE db_script_string SET content_loc3 = 'Es hätte ohne Euch Jahre gedauert das Buch des Raben zu finden, junger Sperber. Kehrt mit unserer Dankbarkeit in Eure Heimat nach Nagrand zurück.' WHERE ( entry = 2000000005);
UPDATE db_script_string SET content_loc3 = 'Sie verfolgen mich, $R! Schnell, erzählt mir warum Ihr hier seid bevor wir entdeckt werden! Wenn sie mich fangen, wird das meinen Tod bedeuten und Eurer ebenfalls!' WHERE ( entry = 2000000006);
UPDATE db_script_string SET content_loc3 = 'Ihr -- Ihr seid nicht einer von ihnen! Lasst und hier verschwinden bevor sie uns finden! Beeilt Euch!' WHERE ( entry = 2000000007);
UPDATE db_script_string SET content_loc3 = 'Was macht ihr im Reich von Ysera, Eindringling? Fort von hier, sage ich! Eure Sorte ist hier nicht willkommen!' WHERE ( entry = 2000000008);
UPDATE db_script_string SET content_loc3 = 'Die Gefahr wird bald vorüber sein! $N wird uns alle beschützen!' WHERE ( entry = 2000000009);
UPDATE db_script_string SET content_loc3 = 'Wieviele von euch Grunzern muss ich noch zu Mammi und Daddi in einem Leichensack zurückschicken, bevor ihr versteht und einseht, dass es Selbstmord ist mit dem Kopf voraus in eine Gruppe von Legionskillern zu laufen? Und nickt nicht mit euren dicken Schädeln als würdet ihr wissen von was ich sage!' WHERE ( entry = 2000000010);
UPDATE db_script_string SET content_loc3 = 'Gut, das sollte seinen Zweck erfüllen. Kommt nun, lasst uns zurück zu dem Verkaufsstand gehen, um unser Geschäft abzuschließen!' WHERE ( entry = 2000000011);
UPDATE db_script_string SET content_loc3 = 'Folgt mir, lieber $C. Ich werde euer Pferdegeschirr schneller fertig gestellt haben, als ich einen stämmigen Zwerg bezwingen kann. Mmmm... stämmig.' WHERE ( entry = 2000000012);
UPDATE db_script_string SET content_loc3 = 'Danke, großer Geist. Herzlichen Dank!' WHERE ( entry = 2000000016);
UPDATE db_script_string SET content_loc3 = 'Geister des Wassers, ich preise euch an, und ich bitte euch um einen Gefallen. Ihr habt die Bitten von $N gehört, und ich verlasse mich darauf, dass seine Ansicht edel ist. Bitte, würdet ihr uns beistehen?' WHERE ( entry = 2000000026);
UPDATE db_script_string SET content_loc3 = 'Das Volk von Westfall salutiert vor $N, einem mutigen und tapferen Verteidiger der Freiheit.' WHERE ( entry = 2000000028);
UPDATE db_script_string SET content_loc3 = 'Oooooo heiß heiß heiß! Wenn euch dies nun nicht dazu gebracht hat euch zu beeilen, dann weiß ich nicht weiter!' WHERE ( entry = 2000000033);
UPDATE db_script_string SET content_loc3 = 'Es geht doch nichts über ein heißes - neee, KOCHENDHEISSES Morgengebräu an einem kalten Wintertag, um einem das Herz zu wärmen!' WHERE ( entry = 2000000035);
UPDATE db_script_string SET content_loc3 = 'Hört, hört, Bewohner von Tanaris! Lasst es alle wissen: $N ist ein exzellentes Mitglied des Mithrilordens. Ein Schmied mit Ehre, Engagement und grenzenloser Geduld. Ein dreifaches Hoch auf $N!' WHERE ( entry = 2000000041);
UPDATE db_script_string SET content_loc3 = 'Friede und Geduld sei mit Euch, $N. Bleibt immer stark.' WHERE ( entry = 2000000042);
UPDATE db_script_string SET content_loc3 = 'Bis wir uns wieder treffen, sei tapfer.' WHERE ( entry = 2000000043);
UPDATE db_script_string SET content_loc3 = 'Nun lass uns diese Rare Erde in meinen Übertopf stecken...' WHERE ( entry = 2000000048);
UPDATE db_script_string SET content_loc3 = 'Vielen Dank nochmal, $N. Diese Rare Erde wird mir bei meinen Experimenten sehr nützlich sein.' WHERE ( entry = 2000000049);
UPDATE db_script_string SET content_loc3 = 'Whoops!' WHERE ( entry = 2000000068);
UPDATE db_script_string SET content_loc3 = 'Das ist interessant...' WHERE ( entry = 2000000069);
UPDATE db_script_string SET content_loc3 = 'Ich muss Noram und Horatio kontaktieren.' WHERE ( entry = 2000000070);
UPDATE db_script_string SET content_loc3 = 'Seid geduldig $N. Die Lampe ist fast fertig.' WHERE ( entry = 2000000072);
UPDATE db_script_string SET content_loc3 = 'Es ist vollbracht...' WHERE ( entry = 2000000073);
UPDATE db_script_string SET content_loc3 = 'Es ist zwar ein Geheimnis der Vergangenheit! Aber es ist ein Schlüssel für unsere Zukunft!' WHERE ( entry = 2000000079);
UPDATE db_script_string SET content_loc3 = 'Bei den Sternen! Ein Geist wurde beschworen!' WHERE ( entry = 2000000089);
UPDATE db_script_string SET content_loc3 = 'Wir werden keine Dämonendiener in unsere Ländern dulden!' WHERE ( entry = 2000000090);
UPDATE db_script_string SET content_loc3 = 'Ribbit! Nein!! Das kann nicht sein...Ribbit...! Du hast mich hinters Licht geführt mit...Ribbit...deine garstige Betrügerei! Ribbit!' WHERE ( entry = 2000000091);
UPDATE db_script_string SET content_loc3 = 'Das dürfte nicht lange dauern...' WHERE ( entry = 2000000099);
UPDATE db_script_string SET content_loc3 = '$N gegen den grausamen Grollhuf, Schmetterzehe!' WHERE ( entry = 2000000102);
UPDATE db_script_string SET content_loc3 = 'Der Kampf wird bald beginnen!' WHERE ( entry = 2000000103);
UPDATE db_script_string SET content_loc3 = 'Gehe in den Ring des Blutes, $N. Der Kampf wird bald beginnen!' WHERE ( entry = 2000000104);
UPDATE db_script_string SET content_loc3 = '%s untersucht die Schnappkieferschalen...' WHERE ( entry = 2000000108);
UPDATE db_script_string SET content_loc3 = 'Hm...' WHERE ( entry = 2000000109);
UPDATE db_script_string SET content_loc3 = 'Seltsam. Sehr seltsam...' WHERE ( entry = 2000000110);
UPDATE db_script_string SET content_loc3 = '$N. Diese Schalen sagen viel aus, aber ich fürchte, es stellen sich nun noch viel mehr Fragen...' WHERE ( entry = 2000000111);
UPDATE db_script_string SET content_loc3 = 'Zarlman Zwillingsmond beginnt zu singen, wärend er die Quellsteine und das Bernsteinkorn vor dem Stammesfeuer vermischt.' WHERE ( entry = 2000000112);
UPDATE db_script_string SET content_loc3 = 'Das Wasser der Seher steht für Euch zum Trinken bereit, $N.' WHERE ( entry = 2000000113);
UPDATE db_script_string SET content_loc3 = 'Und sogar noch mehr!' WHERE ( entry = 2000000118);
UPDATE db_script_string SET content_loc3 = 'Passt auf! Es kommen noch mehr!' WHERE ( entry = 2000000119);
UPDATE db_script_string SET content_loc3 = 'Schaut! Diener Terokks nähern sich!' WHERE ( entry = 2000000120);
UPDATE db_script_string SET content_loc3 = 'Ein Avatar Terokks! Zu den Waffen!' WHERE ( entry = 2000000121);
UPDATE db_script_string SET content_loc3 = 'Fürst Illidan wird hier bald eintreffen.' WHERE ( entry = 2000000126);
UPDATE db_script_string SET content_loc3 = 'Seid gegrüßt Fürst Illidan!' WHERE ( entry = 2000000127);
UPDATE db_script_string SET content_loc3 = 'Weitergehen!' WHERE ( entry = 2000000132);
UPDATE db_script_string SET content_loc3 = 'Wie kann irgendjemand so leben!?' WHERE ( entry = 2000000143);
UPDATE db_script_string SET content_loc3 = 'Das muss repariert werden!' WHERE ( entry = 2000000144);
UPDATE db_script_string SET content_loc3 = 'Das funktioniert niemals...' WHERE ( entry = 2000000145);
UPDATE db_script_string SET content_loc3 = 'ICH WERDE ALLES ZERSTÖREN' WHERE ( entry = 2000000149);
UPDATE db_script_string SET content_loc3 = 'UNS ALLE, MEHR UND MEHR' WHERE ( entry = 2000000150);
UPDATE db_script_string SET content_loc3 = 'Gewinne! Holt Eure Gewinne direkt hier ab! Kommt her und löst Eure Gewinnlose des Dunkelmond-Jahrmarkts gegen wertvolle Gewinne ein!' WHERE ( entry = 2000000157);
UPDATE db_script_string SET content_loc3 = 'Kommt sprecht mit mir, und was einst verschwommen war soll kristallklar werden.' WHERE ( entry = 2000000158);
UPDATE db_script_string SET content_loc3 = 'Ahh, meine kostbare Ameenah! Wie schön dich wieder zu sehen.' WHERE ( entry = 2000000164);
UPDATE db_script_string SET content_loc3 = 'Yer ist tot, Prinzessin, ich kann es fühlen!' WHERE ( entry = 2000000165);
UPDATE db_script_string SET content_loc3 = 'Hmm, macht Euch keine Sorgen, denn ich mache es!' WHERE ( entry = 2000000166);
UPDATE db_script_string SET content_loc3 = 'Sie sagen er kann sich manchmal in einen Raben verwandeln.' WHERE ( entry = 2000000167);
UPDATE db_script_string SET content_loc3 = 'Und dann hat der Hase einfach seinen Kopf abgebissen... Ich schwöre es.' WHERE ( entry = 2000000168);
UPDATE db_script_string SET content_loc3 = 'Ich schwöre Euch, manche haben sie bereits gesehen. Pandaria existieren wirklich!!' WHERE ( entry = 2000000169);
UPDATE db_script_string SET content_loc3 = 'Wisst Ihr warum die Augen von Orcs rot glühen? Dies ist so, weil sie Blut trinken!' WHERE ( entry = 2000000170);
UPDATE db_script_string SET content_loc3 = 'Ich glaube nicht, dass es irgendwelche Fische in diesen Kanälen gibt.' WHERE ( entry = 2000000171);
UPDATE db_script_string SET content_loc3 = 'Und dies ist die Geschichte, wie Lother sechsunddreißig Orcs mit seinen bloßen Händen tötete!' WHERE ( entry = 2000000172);
UPDATE db_script_string SET content_loc3 = 'Ähh... das ist kein Fisch!' WHERE ( entry = 2000000173);
UPDATE db_script_string SET content_loc3 = 'Ich habe Eingeweide von Würmern auf meinen Schuhen.' WHERE ( entry = 2000000174);
UPDATE db_script_string SET content_loc3 = 'Ich glaube ich sehe etwas.' WHERE ( entry = 2000000175);
UPDATE db_script_string SET content_loc3 = 'Ich hoffe das war ein Fisch!' WHERE ( entry = 2000000176);
UPDATE db_script_string SET content_loc3 = 'Wurm geht auf den Haken, der Haken geht in''s Wasser, Fische sind im Wasser, unsere Fische.' WHERE ( entry = 2000000177);
UPDATE db_script_string SET content_loc3 = 'Könnt Ihr Euch das vorstellen?' WHERE ( entry = 2000000178);
UPDATE db_script_string SET content_loc3 = 'Wirklich?' WHERE ( entry = 2000000179);
UPDATE db_script_string SET content_loc3 = 'Wow!' WHERE ( entry = 2000000180);
UPDATE db_script_string SET content_loc3 = 'Mein Vater sagt es ist bloß eine Geschichte.' WHERE ( entry = 2000000181);
UPDATE db_script_string SET content_loc3 = 'Das ist hübsch.' WHERE ( entry = 2000000182);
UPDATE db_script_string SET content_loc3 = 'Ich werde niemals aufhören. Niemals...' WHERE ( entry = 2000000183);
UPDATE db_script_string SET content_loc3 = 'Armer Dorius. Falls ich jemals diese Dunkeleisen erwische, dann helft mir...' WHERE ( entry = 2000000194);
UPDATE db_script_string SET content_loc3 = 'Es entkommt!' WHERE ( entry = 2000000195);
UPDATE db_script_string SET content_loc3 = 'Kommt herein einzelner, kommt alle herein! Willkommen zum Dunkelmond-Jahrmarkt! Ersehnt ihr Abenteuer? Begehrt Ihr exotische und geheimnisvolle Schätze? Dann müsst Ihr nicht mehr länger suchen! Ihr, mein Freund, seid zum richtigen Ort gekommen! Taucht ein und seid ein Teil von allem was der Jahrmarkt zu bieten hat! Wir werden die ganze Woche an diesem Ort sein, also geht sicher, dass es auch Eure Freunde und Geliebten erfahren!' WHERE ( entry = 2000000198);
UPDATE db_script_string SET content_loc3 = 'Willkommen beim Dunkelmond-Jahrmarkt, der größten Veranstaltung in allen Welten! Wir haben alles... köstliches Essen, starke Getränke, exotische Artefakte, Wahrsager, erstaunliche Gewinne und Aufregung ohne Ende! Vergesst nicht Eure Gewinnlose des Dunkelmond-Jahrmarkts bei Gelvas Rußgatter einzuwechseln! Alles was Ihr braucht sind fünf oder mehr und Ihr seid auf dem Weg zu den wundersamsten Gewinnen in der gesamten Scherbenwelt. Jeder ist ein Gewinner' WHERE ( entry = 2000000199);
UPDATE db_script_string SET content_loc3 = 'Mammi? Kann ich Frizzles streicheln?' WHERE ( entry = 2000000200);
UPDATE db_script_string SET content_loc3 = 'Ducken!' WHERE ( entry = 2000000201);
UPDATE db_script_string SET content_loc3 = 'Geht nicht zu nah an den See! Er ist verflucht!' WHERE ( entry = 2000000202);
UPDATE db_script_string SET content_loc3 = 'Ich werde mein Bestes geben um auf die Kinder aufzupassen, Großmutter.' WHERE ( entry = 2000000203);
UPDATE db_script_string SET content_loc3 = 'Nun dann zeigt mal her und wir schauen was Ihr erreicht habt!' WHERE ( entry = 2000000204);
UPDATE db_script_string SET content_loc3 = 'Klasse, Gazlowe!' WHERE ( entry = 2000000205);
UPDATE db_script_string SET content_loc3 = 'Ich habe eine weitere Lesung aus dem Nether.' WHERE ( entry = 2000000206);
UPDATE db_script_string SET content_loc3 = 'Genau. Wir haben gerade unsere Rücken ruiniert um all diesen Kram hier hoch zu schleppen, und Ihr wollt, dass wir noch mehr arbeiten?' WHERE ( entry = 2000000207);
UPDATE db_script_string SET content_loc3 = 'Der Wind berichtet von den Bewegungen unserer Gegner, Ashyen. Die Naga werden erneut angreifen.' WHERE ( entry = 2000000208);
UPDATE db_script_string SET content_loc3 = 'Sehr gut. Wenn diese Entscheidung getroffen wurde, werde ich bereit sein. Lasst uns hoffen, dass es nicht zu spät sein wird.' WHERE ( entry = 2000000209);
UPDATE db_script_string SET content_loc3 = 'Nach dieser Schicht werde ich diesem Kopfgeld mal nachgehen.' WHERE ( entry = 2000000210);
UPDATE db_script_string SET content_loc3 = 'Ihr wollt zu diesem Steckbrief zurückkehren, wenn Ihr eure Aufgabe erfüllt habt?' WHERE ( entry = 2000000211);
UPDATE db_script_string SET content_loc3 = 'Seid der erste aus Eurem Umfeld der den unglaublichen elektrostatischen Makulaturblaster besitzt!' WHERE ( entry = 2000000212);
UPDATE db_script_string SET content_loc3 = 'Abgeleitet von innovativer Militärtechnologie der Offensive der Zerschmetterten Hand, es entfernt hartnäckige Flecken mit Leichtigkeit!' WHERE ( entry = 2000000213);
UPDATE db_script_string SET content_loc3 = 'Weinflecken, Grasflecken, ja sogar Haustierflecken sind dem Elektrostatischen Makulatios-Sprenger nicht gewachsen!' WHERE ( entry = 2000000214);
UPDATE db_script_string SET content_loc3 = 'Zögert nicht! Bestellt jetzt und erhaltet mein Ultra-Kinetisches Waffeleisen ohne zusätzliche Gebühren!' WHERE ( entry = 2000000215);
UPDATE db_script_string SET content_loc3 = 'Es kommt mit uns mit, Waffelfritte. Habt Ihr keine Produktdemonstration oder etwas ähnliches zu tun?' WHERE ( entry = 2000000216);
UPDATE db_script_string SET content_loc3 = 'Redet! Wo versteckt sich Euer Anführer?' WHERE ( entry = 2000000217);
UPDATE db_script_string SET content_loc3 = 'Bitte! Ich muss bald etwas fressen... Einen Manakristall... einen Splitter... irgendetwas! Der Schmerz ist unerträglich!' WHERE ( entry = 2000000218);
UPDATE db_script_string SET content_loc3 = 'Fragt einfach nicht woher ich es habe...' WHERE ( entry = 2000000219);
UPDATE db_script_string SET content_loc3 = 'Vielleicht sollte ich einfach auf die Jagd nach dieser elenden Bestie gehen, jetzt wo eine Belohnung auf ihren Kopf ausgesetzt ist.' WHERE ( entry = 2000000220);
UPDATE db_script_string SET content_loc3 = 'Die hinteren Wände sind komplett weggesprengt!' WHERE ( entry = 2000000223);
UPDATE db_script_string SET content_loc3 = 'Sie nennen das Schwitzen!..' WHERE ( entry = 2000000224);
UPDATE db_script_string SET content_loc3 = 'Das muss repariert werden..' WHERE ( entry = 2000000225);
UPDATE db_script_string SET content_loc3 = 'BETET, DASS IHR MIR DIENEN DÜRFT' WHERE ( entry = 2000000228);
UPDATE db_script_string SET content_loc3 = 'Lose! Löst Eure Gewinnlose des Dunkelmond-Jahrmarkts hier ein! Wundersame und exotische Preise warten auf Euch!' WHERE ( entry = 2000000229);
UPDATE db_script_string SET content_loc3 = 'Fürchtet Euch nicht! Alle Schicksale können für diejenigen, die wissen wie, wargenommen werden.' WHERE ( entry = 2000000230);
UPDATE db_script_string SET content_loc3 = 'Hey, kann mir jemand helfen dies hier zu fangen!' WHERE ( entry = 2000000231);
UPDATE db_script_string SET content_loc3 = 'Ämusiert sich jeder bis jetzt? Das ist perfekt! Willkommen auf dem Dunkelmond-Jahrmarkt, die beste Show in der ganzen Scherbenwelt! Geht sicher, dass Ihr hier mit Yebb und seinen Freunden sprecht, während Ihr Nabetands Dünkelmond Zoo Bizarre nehmt.' WHERE ( entry = 2000000232);
UPDATE db_script_string SET content_loc3 = 'Seid gegrüßt Freunde, und herzlich willkommen bei der besten Show in Azeroth!$B$BBitte, kommt herein und nehmt alles wahr, was wir anzubieten haben. Reitet aus und seht die Sehenswürdigkeiten! Lasst Euch von den Wundern, die der Dunkelmond-Jahrmarkt in dieser Wüsten und mysteriösen welt aufgedeckt hat! Wir haben keine Mühen gescheit, um Euch Aufregung zu bringen, bei der Kinder jeden Alters Vergnügung finden werden!' WHERE ( entry = 2000000233);
UPDATE db_script_string SET content_loc3 = 'Diese Informationen werden ziemlich nützlich für das Projekt Blue Book sein. Äh, ich meine sie werden großartig für mein neues Aussehen sein. Schaut, ob Ihr noch mehr Daten sammeln könnt.' WHERE ( entry = 2000000234);
UPDATE db_script_string SET content_loc3 = 'ICH GEMEINER OGER' WHERE ( entry = 2000000235);
UPDATE db_script_string SET content_loc3 = 'ICH SPÜRE DEN TOT KOMMEN' WHERE ( entry = 2000000236);
UPDATE db_script_string SET content_loc3 = 'Kommt zu mir Ihr wahren Gläubigen, und seht was die Zukunft Euch bringen wird!' WHERE ( entry = 2000000237);
UPDATE db_script_string SET content_loc3 = 'KEINER WIRD AN MIR VORBEIKOMMEN' WHERE ( entry = 2000000239);
UPDATE db_script_string SET content_loc3 = 'Je länger Ihr wartet, umso weniger Zukunft habt Ihr für mich zum vorhersagen.' WHERE ( entry = 2000000240);
UPDATE db_script_string SET content_loc3 = 'Nehmt eine Kerze des Heranlockens aus dieser Kiste, $N.' WHERE ( entry = 2000000244);
UPDATE db_script_string SET content_loc3 = 'M... m... mir... geht... es... nicht... gut...' WHERE ( entry = 2000000245);
UPDATE db_script_string SET content_loc3 = 'Mein Verstand... mein Fleisch... ich... verwese...!' WHERE ( entry = 2000000246);
UPDATE db_script_string SET content_loc3 = 'Ich erhebe mein Glas und hoffe, dass wir Euresgleichen bald los sind! Prost, Ihr nichtsnutziger Halunke, $N!' WHERE ( entry = 2000000247);
UPDATE db_script_string SET content_loc3 = 'Onu betrachtet das Pergament aus dem Folianten der Schattenhammerkultisten...' WHERE ( entry = 2000000249);
UPDATE db_script_string SET content_loc3 = 'Onu wird von freigesetzter Magie getroffen' WHERE ( entry = 2000000250);
UPDATE db_script_string SET content_loc3 = 'Hmmm...' WHERE ( entry = 2000000251);
UPDATE db_script_string SET content_loc3 = 'Terenthis beginnt, einen Zauber zu wirken, als Ihr ihm den Umhang abnehmt.' WHERE ( entry = 2000000252);
UPDATE db_script_string SET content_loc3 = 'Geht jetzt, $N. Findet Volcor... und denkt daran, dass die Magie, die Euch beschützt, versagen wird, wenn Ihr mit anderen mehr tut als bloß zu reden.' WHERE ( entry = 2000000253);
UPDATE db_script_string SET content_loc3 = 'Großmutter Falkenwind deutet auf die Wasserkanne, die auf dem Rand des Brunnens steht.' WHERE ( entry = 2000000254);
UPDATE db_script_string SET content_loc3 = 'Diesen Seelenstein zu zerbrechen ist eine ziemlich einfache Aufgabe!' WHERE ( entry = 2000000255);
UPDATE db_script_string SET content_loc3 = 'Leuchtender Seelenstein springt auf!' WHERE ( entry = 2000000256);
UPDATE db_script_string SET content_loc3 = 'Dann müssen wir Athrikus Narassin beseitigen. Sagt mir, Geist, wo kann ich die anderen Seelensteine finden, um seine Magie rückgängig zu machen?' WHERE ( entry = 2000000257);
UPDATE db_script_string SET content_loc3 = 'Sargath verschwindet im Nebel...' WHERE ( entry = 2000000258);
UPDATE db_script_string SET content_loc3 = 'Ich sollte jetzt sofort beginnen, $N.' WHERE ( entry = 2000000259);
UPDATE db_script_string SET content_loc3 = 'So... wo sind Nadel und Faden? Ah! Da sind sie ja...' WHERE ( entry = 2000000260);
UPDATE db_script_string SET content_loc3 = 'Beeilt Euch, $N. Benutzt das Portal!' WHERE ( entry = 2000000261);
UPDATE db_script_string SET content_loc3 = 'Na gut, sehen wir uns das Ding da mal an...' WHERE ( entry = 2000000262);
UPDATE db_script_string SET content_loc3 = 'Oh, verdammt...' WHERE ( entry = 2000000263);
UPDATE db_script_string SET content_loc3 = 'Die Geister des Steinkrallengebirges wüten noch immer, $N.' WHERE ( entry = 2000000264);
UPDATE db_script_string SET content_loc3 = 'Ich fürchte, wir werden sie niemals beschwichtigen können...' WHERE ( entry = 2000000265);
UPDATE db_script_string SET content_loc3 = 'Na gut! Dann mal los!' WHERE ( entry = 2000000266);
UPDATE db_script_string SET content_loc3 = '... Uups.' WHERE ( entry = 2000000267);
UPDATE db_script_string SET content_loc3 = 'He, $N! Vergesst nicht, eine Kiste, ein Handbuch und einen Leitstecken mitzunehmen!' WHERE ( entry = 2000000268);
UPDATE db_script_string SET content_loc3 = 'Habt abermals Dank für Eure Hilfe. Möge Euch bei Euren Reisen der Wind im Rücken stehen.' WHERE ( entry = 2000000269);
UPDATE db_script_string SET content_loc3 = 'Okay, Leute. Macht euch an die Arbeit und bringt diese Knochen an.' WHERE ( entry = 2000000276);
UPDATE db_script_string SET content_loc3 = '%s saugt etwas Traumstaub in die Nase...' WHERE ( entry = 2000000277);
UPDATE db_script_string SET content_loc3 = '%s ist benommen...' WHERE ( entry = 2000000278);
UPDATE db_script_string SET content_loc3 = 'Hatschi!' WHERE ( entry = 2000000279);
UPDATE db_script_string SET content_loc3 = 'Unglaublich! $N, dieser Traumstaub ist aber ein Teufelszeug!' WHERE ( entry = 2000000280);
UPDATE db_script_string SET content_loc3 = '%s trinkt einen großen Schluck Bier.' WHERE ( entry = 2000000281);
UPDATE db_script_string SET content_loc3 = 'Das war erfrischend. Jetzt zu den Informationen, die ich loswerden muss...' WHERE ( entry = 2000000282);
UPDATE db_script_string SET content_loc3 = 'Ich denke, dass die Verlassenen die Verbündeten der horde in die Irre führen... wartet... ich fühle mich so... benommen...' WHERE ( entry = 2000000283);
UPDATE db_script_string SET content_loc3 = '%s windet sich vor Schmerzen.' WHERE ( entry = 2000000284);
UPDATE db_script_string SET content_loc3 = 'AAAAAAAARGH!' WHERE ( entry = 2000000285);
UPDATE db_script_string SET content_loc3 = 'Hmm... ich frage mich...' WHERE ( entry = 2000000286);
UPDATE db_script_string SET content_loc3 = 'Nun, wo ist es?' WHERE ( entry = 2000000287);
UPDATE db_script_string SET content_loc3 = 'Dumme Magier... verbrauchen alle Reagenzien und besorgen nie Ersatz.' WHERE ( entry = 2000000288);
UPDATE db_script_string SET content_loc3 = 'Danke, $N.' WHERE ( entry = 2000001008);
UPDATE db_script_string SET content_loc3 = 'Heulsuse! Heulsuse!' WHERE ( entry = 2000005057);
UPDATE db_script_string SET content_loc3 = 'Das Baby möchte ihre Puppe zurück!' WHERE ( entry = 2000005058);
UPDATE db_script_string SET content_loc3 = 'Ich frag'' mich ob deine Puppe schwimmen kann!' WHERE ( entry = 2000005059);
UPDATE db_script_string SET content_loc3 = 'Haha! Ich habe Betsy!' WHERE ( entry = 2000005060);
UPDATE db_script_string SET content_loc3 = 'Ich habe deine Puppe! Nana, nana!' WHERE ( entry = 2000005062);
UPDATE db_script_string SET content_loc3 = 'Gib'' mir meine Puppe!!' WHERE ( entry = 2000005078);
UPDATE db_script_string SET content_loc3 = 'Tu Betsy nicht weh, du Fiesling!' WHERE ( entry = 2000005080);
UPDATE db_script_string SET content_loc3 = 'Zwölf Fokuszentren einzubringen könnte es den magischen Energien erlauben, sich stabiler zu formen, da sie die notwendige Stabilität einbringen.' WHERE ( entry = 2000005148);
UPDATE db_script_string SET content_loc3 = 'Wenigstens wären wir nicht hier, um es saubermachen zu müssen.' WHERE ( entry = 2000005149);
UPDATE db_script_string SET content_loc3 = 'Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.' WHERE ( entry = 2000005150);
UPDATE db_script_string SET content_loc3 = 'Die resultierenden Energien könnten natürlich kollabieren und das könnte wiederum einen Energiefluss erzeugen, der Euch die nächsten Wochen eine Migräne bescheren würde.' WHERE ( entry = 2000005151);
UPDATE db_script_string SET content_loc3 = 'Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.' WHERE ( entry = 2000005152);
UPDATE db_script_string SET content_loc3 = 'Nur, wenn wir nicht die richtigen Initialisierungsprozeduren befolgen.' WHERE ( entry = 2000005153);
UPDATE db_script_string SET content_loc3 = 'Wenigstens wären wir nicht hier, um es saubermachen zu müssen.' WHERE ( entry = 2000005154);
UPDATE db_script_string SET content_loc3 = 'Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?' WHERE ( entry = 2000005155);
UPDATE db_script_string SET content_loc3 = 'Ich denke, dass es funktionieren könnte, wenn wir zum Zaubern zwanzig Leute zur Verfügung hätten.' WHERE ( entry = 2000005156);
UPDATE db_script_string SET content_loc3 = 'Aber was passiert, wenn die resultierende Frequenzverschiebung eine magische Rückkopplung durch die Ströme schickt?' WHERE ( entry = 2000005157);
UPDATE db_script_string SET content_loc3 = 'Das wird jedoch den magischen Fokus aus der Balance bringen und im Äther eine umgekehrte Vibration verursachen' WHERE ( entry = 2000005159);
UPDATE db_script_string SET content_loc3 = 'Warum können wir nicht einfach den Bereich ändern, um die Abweichung der Durchflussmenge auszugleichen?' WHERE ( entry = 2000005161);
UPDATE db_script_string SET content_loc3 = 'Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?' WHERE ( entry = 2000005162);
UPDATE db_script_string SET content_loc3 = 'Ich denke nicht. Ich möchte nicht wieder hochgejagt werden.' WHERE ( entry = 2000005163);
UPDATE db_script_string SET content_loc3 = 'Maginor sagt, dass Wechselströme positiver Energie in der Tat einen viel stabileren Fluss erzeugen.' WHERE ( entry = 2000005164);
UPDATE db_script_string SET content_loc3 = 'Aber ist es nicht genau das, was die anfänglichen Probleme mit Adept Sylerias magischen Formeln verursachte?' WHERE ( entry = 2000005166);
UPDATE db_script_string SET content_loc3 = 'Wenn wir die Essenzströme umkehren, können wir vielleicht auch die Polarität ändern.' WHERE ( entry = 2000005169);
UPDATE db_script_string SET content_loc3 = 'Was wäre denn, wenn wir drei Fokusse nach tyreanischem Muster einsetzen? Das sollte die Lösung sein.' WHERE ( entry = 2000005170);
UPDATE db_script_string SET content_loc3 = 'Hui, und das alles für einen liebestrank. Hoffentlich ist er es wert.' WHERE ( entry = 2000005171);
UPDATE db_script_string SET content_loc3 = 'Wenn wir eine geeignete Sequenz benutzen, sollte es funktionieren. Es werden vor Beginn nur sorgfältige Studien nötig sein.' WHERE ( entry = 2000005172);
UPDATE db_script_string SET content_loc3 = 'Das Portal würde sich leicht verlagern. Wenn Ihr zu diesem Zeitpunkt einen Bindezauberspruch sprecht, könnt Ihr es an Ort und Stelle verfestigen.' WHERE ( entry = 2000005173);
UPDATE db_script_string SET content_loc3 = 'Hui, und das alles für einen liebestrank. Hoffentlich ist er es wert.' WHERE ( entry = 2000005174);
UPDATE db_script_string SET content_loc3 = 'Aber wenn wir es mit einem Ankergewinde auf angemessenem Energiefluss stabilisieren könnten, sollte es funktionieren.' WHERE ( entry = 2000005175);
UPDATE db_script_string SET content_loc3 = 'Was wäre denn, wenn wir drei Fokusse nach tyreanischem Muster einsetzen? Das sollte die Lösung sein.' WHERE ( entry = 2000005176);
UPDATE db_script_string SET content_loc3 = 'Wenn wir eine geeignete Sequenz benutzen, sollte es funktionieren. Es werden vor Beginn nur sorgfältige Studien nötig sein.' WHERE ( entry = 2000005177);
UPDATE db_script_string SET content_loc3 = 'Aber wenn wir es mit einem Ankergewinde auf angemessenem Energiefluss stabilisieren könnten, sollte es funktionieren.' WHERE ( entry = 2000005178);
UPDATE db_script_string SET content_loc3 = 'Hui, und das alles für einen liebestrank. Hoffentlich ist er es wert.' WHERE ( entry = 2000005179);
UPDATE db_script_string SET content_loc3 = 'Die magischen Studien belasten Euer Gehirn? Entspannt Euch im Blauen Eremiten!' WHERE ( entry = 2000005185);
UPDATE db_script_string SET content_loc3 = 'Die besten Getränke von ganz Sturmwind!' WHERE ( entry = 2000005186);
UPDATE db_script_string SET content_loc3 = 'Auf zum Blauen Eremiten. Dort kennt jeder Euren Namen!' WHERE ( entry = 2000005187);
UPDATE db_script_string SET content_loc3 = 'Seid Ihr deprimiert? Kommt zum Blauen Eremiten und habt Spaß!' WHERE ( entry = 2000005188);
UPDATE db_script_string SET content_loc3 = 'Die besten Getränke von ganz Sturmwind!' WHERE ( entry = 2000005189);
UPDATE db_script_string SET content_loc3 = 'Die magischen Studien belasten Euer Gehirn? Entspannt Euch im Blauen Eremiten!' WHERE ( entry = 2000005190);
UPDATE db_script_string SET content_loc3 = 'Fragt mich, wenn Ihr wissen wollt, wie man im Blauen Eremiten ein Getränk umsonst bekommt!' WHERE ( entry = 2000005191);
UPDATE db_script_string SET content_loc3 = 'Auf zum Blauen Eremiten. Dort kennt jeder Euren Namen!' WHERE ( entry = 2000005192);
UPDATE db_script_string SET content_loc3 = 'Kostenlose Getränke im Blauen Eremiten!' WHERE ( entry = 2000005193);
UPDATE db_script_string SET content_loc3 = 'Seid Ihr deprimiert? Kommt zum Blauen Eremiten und habt Spaß!' WHERE ( entry = 2000005194);
UPDATE db_script_string SET content_loc3 = 'Die magischen Studien belasten Euer Gehirn? Entspannt Euch im Blauen Eremiten!' WHERE ( entry = 2000005195);
UPDATE db_script_string SET content_loc3 = 'Die besten Getränke von ganz Sturmwind!' WHERE ( entry = 2000005196);
UPDATE db_script_string SET content_loc3 = 'Fragt mich, wenn Ihr wissen wollt, wie man im Blauen Eremiten ein Getränk umsonst bekommt!' WHERE ( entry = 2000005197);
UPDATE db_script_string SET content_loc3 = 'Auf zum Blauen Eremiten. Dort kennt jeder Euren Namen!' WHERE ( entry = 2000005198);
UPDATE db_script_string SET content_loc3 = 'Die besten Getränke von ganz Sturmwind!' WHERE ( entry = 2000005199);
UPDATE db_script_string SET content_loc3 = 'Diese Feuer müssen jahrelang gebrannt haben. Ein für Trolle ungewöhnlicher Brauch.' WHERE ( entry = 2000005237);
UPDATE db_script_string SET content_loc3 = 'Seltsam... dieses Mosaik ähnelt keiner der bekannten Trolltraditionen.' WHERE ( entry = 2000005238);
UPDATE db_script_string SET content_loc3 = 'Ja, ja, ich bin mir ziemlich sicher, dass dies hier die spirituelle Vereinigung unterschiedlicher Wesen darstellt. Faszinierend.' WHERE ( entry = 2000005239);
UPDATE db_script_string SET content_loc3 = 'Mann kann oft Erstaunliches über eine Kultur erfahren, indem man ihre Abfälle studiert.' WHERE ( entry = 2000005240);
UPDATE db_script_string SET content_loc3 = 'Igitt. Verfilzte Haarklumpen, ausgerissene Federn, Knochensplitter, zum Teil verbranntes Material - Kleidung vielleicht?' WHERE ( entry = 2000005241);
UPDATE db_script_string SET content_loc3 = 'VERBEUGT EUCH VOR DEM ALLMÄCHTIGEN! VERBEUGT EUCH VOR MEINEM FÜRCHTERLICHEN ZERSTÖR... Hühnchen?' WHERE ( entry = 2000000013);
UPDATE db_script_string SET content_loc3 = 'Bleibt zurück! Haltet Abstand! Das Fürchterliche neigt dazu einen großen Bogen zu machen!' WHERE ( entry = 2000000014);
UPDATE db_script_string SET content_loc3 = 'Seid still, Diener! Die Rache wird mein sein! Tot ganz Sturmwind! Tot durch das Hühnchen!' WHERE ( entry = 2000000015);
UPDATE db_script_string SET content_loc3 = 'Weggetreten, $N.' WHERE ( entry = 2000000017);
UPDATE db_script_string SET content_loc3 = 'Ihr müsst mich auf unserem Weg beschützen!' WHERE ( entry = 2000000021);
UPDATE db_script_string SET content_loc3 = 'Danke für meine Rettung!' WHERE ( entry = 2000000022);
UPDATE db_script_string SET content_loc3 = 'Danke!' WHERE ( entry = 2000000024);
UPDATE db_script_string SET content_loc3 = 'Ok, lasst uns gehen' WHERE ( entry = 2000000025);
UPDATE db_script_string SET content_loc3 = 'Lasst uns gehen.' WHERE ( entry = 2000000027);
UPDATE db_script_string SET content_loc3 = 'Das ist Hollees Zelt, aber wo ist Hollee?' WHERE ( entry = 2000000029);
UPDATE db_script_string SET content_loc3 = 'Hier ist es auch nicht. Komisch .... Wo ist es?' WHERE ( entry = 2000000030);
UPDATE db_script_string SET content_loc3 = 'Hmm. Hier ist es nicht. Vielleicht hat es Hollee …' WHERE ( entry = 2000000031);
UPDATE db_script_string SET content_loc3 = 'Hätte nie gedacht, dass dieses Öl Mana ist! Oh, ihr könnt es haben, außer diesem Grek natürlich.' WHERE ( entry = 2000001020);
UPDATE db_script_string SET content_loc3 = 'Nehmt einen Stein vom Tisch. Ihr werdet ihn bald für eure Aufgabe brauchen.' WHERE ( entry = 2000000036);
UPDATE db_script_string SET content_loc3 = 'Helft mir, bitte!' WHERE ( entry = 2000000037);
UPDATE db_script_string SET content_loc3 = 'Ihr seid mein Held!' WHERE ( entry = 2000000038);
UPDATE db_script_string SET content_loc3 = 'Danke für eure Hilfe.' WHERE ( entry = 2000000039);
UPDATE db_script_string SET content_loc3 = 'Okay, lasst uns gehen!' WHERE ( entry = 2000000040);
UPDATE db_script_string SET content_loc3 = 'Ihr müsst mich vor den Monstern schützen, die in diesem Wald leben!' WHERE ( entry = 2000000044);
UPDATE db_script_string SET content_loc3 = 'Dieser Teil des Waldes ist sehr gefährlich für uns. Wir müssen vorsichtig sein!' WHERE ( entry = 2000000045);
UPDATE db_script_string SET content_loc3 = 'Tötet zwei Monster, die bei der Klee Pflanze stehen und dann pflücke ich den Klee.' WHERE ( entry = 2000000046);
UPDATE db_script_string SET content_loc3 = 'Ich pflücke den Klee. Es dauert noch etwas.' WHERE ( entry = 2000000047);
UPDATE db_script_string SET content_loc3 = 'Nun gut. Ich werde jetzt Leute schicken. Wir müssen ihn finden und ihm helfen.' WHERE ( entry = 2000000050);
UPDATE db_script_string SET content_loc3 = 'Wisst ihr wo er ist?' WHERE ( entry = 2000000051);
UPDATE db_script_string SET content_loc3 = 'Volcor ist gegangen?' WHERE ( entry = 2000000052);
UPDATE db_script_string SET content_loc3 = 'Was ist passiert?' WHERE ( entry = 2000000053);
UPDATE db_script_string SET content_loc3 = 'Nähert euch, Anfänger!' WHERE ( entry = 2000000054);
UPDATE db_script_string SET content_loc3 = 'Hm ... Ihr seid nicht so schlecht!' WHERE ( entry = 2000000055);
UPDATE db_script_string SET content_loc3 = 'Sie wollen mich essen! Ihr müsst mir helfen!' WHERE ( entry = 2000000056);
UPDATE db_script_string SET content_loc3 = 'Oh, danke!' WHERE ( entry = 2000000057);
UPDATE db_script_string SET content_loc3 = 'Folgt mir' WHERE ( entry = 2000000062);
UPDATE db_script_string SET content_loc3 = 'Lest die Notizen in meinem Plan. Sie werden unbezahlbar sein, um die Turm Verteidigung zu überwinden' WHERE ( entry = 2000000067);
UPDATE db_script_string SET content_loc3 = 'Ich finde den Grund für euer Leiden' WHERE ( entry = 2000000071);
UPDATE db_script_string SET content_loc3 = 'beeilt euch mein Freund' WHERE ( entry = 2000000074);
UPDATE db_script_string SET content_loc3 = 'Hallo Grimklaue' WHERE ( entry = 2000000076);
UPDATE db_script_string SET content_loc3 = 'Nun, wir werden sehen ... wenn ich mich nicht vertue, es ... hmm ..' WHERE ( entry = 2000000077);
UPDATE db_script_string SET content_loc3 = 'Wir sind entkommen! Danke!' WHERE ( entry = 2000000087);
UPDATE db_script_string SET content_loc3 = 'Hey, Ich hoffe ihr helft mir!' WHERE ( entry = 2000000088);
UPDATE db_script_string SET content_loc3 = 'Hey, Belm! Gib mir n Krug Donnerbier und einen für meinen guten Freund!' WHERE ( entry = 2000000092);
UPDATE db_script_string SET content_loc3 = 'Dein Unsichtbarkeitsschnaps ist fertig, $N.' WHERE ( entry = 2000000094);
UPDATE db_script_string SET content_loc3 = 'Ihr müsst mich beschützen, damit ich meine Bestimmung erfüllen kann!' WHERE ( entry = 2000000098);
UPDATE db_script_string SET content_loc3 = '[PH] Seid gegrüßt, $N.' WHERE ( entry = 2000000107);
UPDATE db_script_string SET content_loc3 = 'Ich … Wir sind machtlos. Illidan fand und lieferte den Drachenmal ihren Anführer – Zuluhed. Dieser Orc war der Verantwortliche für die Gefangennahme und Einkerkerung von Alexstrasza. Wie können wir gegen solche Macht kämpfen?' WHERE ( entry = 2000000116);
UPDATE db_script_string SET content_loc3 = 'Er erbeutete eine Seite! $B$B Und genauso einfach nahm er meinen Kamerad.' WHERE ( entry = 2000000117);
UPDATE db_script_string SET content_loc3 = 'Komm, $N.  Fürst Sturmgrimm erwartet euch.' WHERE ( entry = 2000000124);
UPDATE db_script_string SET content_loc3 = 'Krieger des Drachenmals, schart euch um mich! Einer von uns hat den Rang eines Hochlords erlangt! Neigt eure Köpfe IN Ehrfurcht! Zeigt euren Respekt UND Loyalität dem Hochlord $N!' WHERE ( entry = 2000000125);
UPDATE db_script_string SET content_loc3 = 'Fürst Illidan, das ist das Drachenmal von dem Ich UND andere euch berichteten. Er wird uns zum Sieg führen!' WHERE ( entry = 2000000128);
UPDATE db_script_string SET content_loc3 = 'Aber … mein Fürst, Ich verstehe nicht. $N … $Ger:Sie ist der $R der …' WHERE ( entry = 2000000129);
UPDATE db_script_string SET content_loc3 = 'Es wird erledigt, mein Fürst.' WHERE ( entry = 2000000130);
UPDATE db_script_string SET content_loc3 = 'Ihr dachtet also ihr könntet Mor''ghor hereinlegen, eh? Bevor ihr Fürst Illidan übergeben werdet, lernt ihr ungeahnte Schmerzen kennen. Ich werde freude daran haben meine Rache auszukosten.' WHERE ( entry = 2000000131);
UPDATE db_script_string SET content_loc3 = 'Sturmwind ist in sicheren Händen!' WHERE ( entry = 2000000133);
UPDATE db_script_string SET content_loc3 = 'Der Feind wird nicht passieren!' WHERE ( entry = 2000000134);
UPDATE db_script_string SET content_loc3 = 'Fäden, Fäden für jeden Geschmack' WHERE ( entry = 2000000135);
UPDATE db_script_string SET content_loc3 = 'Brot, heisses Brot.' WHERE ( entry = 2000000136);
UPDATE db_script_string SET content_loc3 = 'Orgrimmar ist in sicheren Händen!' WHERE ( entry = 2000000137);
UPDATE db_script_string SET content_loc3 = 'Wenn ich mich verändere … da sind meine Frau und meine Kinder ...' WHERE ( entry = 2000000138);
UPDATE db_script_string SET content_loc3 = 'Speisen, Getränke!' WHERE ( entry = 2000000139);
UPDATE db_script_string SET content_loc3 = 'Darnassus ist in sicheren Händen!' WHERE ( entry = 2000000140);
UPDATE db_script_string SET content_loc3 = 'Fressen!' WHERE ( entry = 2000000141);
UPDATE db_script_string SET content_loc3 = 'Eisenschmiede ist in sicheren Händen!' WHERE ( entry = 2000000142);
UPDATE db_script_string SET content_loc3 = 'Mehr Arbeit?' WHERE ( entry = 2000000146);
UPDATE db_script_string SET content_loc3 = 'ICH BIN EIN GOTT DER DÄMONEN' WHERE ( entry = 2000000147);
UPDATE db_script_string SET content_loc3 = 'WO MEINE DÄMONENKRÄFTE' WHERE ( entry = 2000000148);
UPDATE db_script_string SET content_loc3 = 'Willkommen im Piratenhafen !!' WHERE ( entry = 2000000151);
UPDATE db_script_string SET content_loc3 = 'Seid gegrüßt mein Soldat !!' WHERE ( entry = 2000000152);
UPDATE db_script_string SET content_loc3 = 'Mein Schwert – Orc Köpfe ab !!' WHERE ( entry = 2000000153);
UPDATE db_script_string SET content_loc3 = 'Hm … Ich feil dich, komm und kämpfe !!' WHERE ( entry = 2000000154);
UPDATE db_script_string SET content_loc3 = 'Uhh … schön Mädchen !!' WHERE ( entry = 2000000155);
UPDATE db_script_string SET content_loc3 = 'Tanaris ist von uns geliehen !! ZzzzZZ' WHERE ( entry = 2000000156);
UPDATE db_script_string SET content_loc3 = 'Ich glaub ich beginnen eine Rille in die Pflastersteine zu laufen' WHERE ( entry = 2000000159);
UPDATE db_script_string SET content_loc3 = 'Als hätte ich in meinem Alter nichts besseres zu tun, als Wassereimer zu tragen' WHERE ( entry = 2000000160);
UPDATE db_script_string SET content_loc3 = 'Wo ist das Wasser, Emma? Hol das Wasser, Emma?' WHERE ( entry = 2000000161);
UPDATE db_script_string SET content_loc3 = 'Wenn ich nich wär, viele wüssten nich wie Wasser aussieht.' WHERE ( entry = 2000000162);
UPDATE db_script_string SET content_loc3 = 'Dejavu. Für einen Moment, Ich dachte ich wäre wieder zurück daheim … vor der Pest' WHERE ( entry = 2000000163);
UPDATE db_script_string SET content_loc3 = 'Hallo, Charys. Hier meine Liste, kannst du mir das suchen, ganz besonders die letzte Zutat?' WHERE ( entry = 2000000184);
UPDATE db_script_string SET content_loc3 = 'Natürlich, Paige. Aber sei brav.' WHERE ( entry = 2000000185);
UPDATE db_script_string SET content_loc3 = 'Dank dir, Charys. Lass uns gehen Paige, mein Engel.' WHERE ( entry = 2000000186);
UPDATE db_script_string SET content_loc3 = 'Wann kommen wir an?' WHERE ( entry = 2000000187);
UPDATE db_script_string SET content_loc3 = 'Wohin gehen wir?' WHERE ( entry = 2000000188);
UPDATE db_script_string SET content_loc3 = 'Warum gehen wir dahin?' WHERE ( entry = 2000000189);
UPDATE db_script_string SET content_loc3 = 'Billy sagt früher war Fizzle ein großer Zauberer. Aber er wurde in einen Hasen verwandelt, weil ein Zauberspruch schief ging.' WHERE ( entry = 2000000190);
UPDATE db_script_string SET content_loc3 = 'Ich will den Turm der Magier sehen' WHERE ( entry = 2000000191);
UPDATE db_script_string SET content_loc3 = 'Warum gehen wir immer den gleichen Weg?' WHERE ( entry = 2000000192);
UPDATE db_script_string SET content_loc3 = 'Meine Füße tun sehr weh.' WHERE ( entry = 2000000193);
UPDATE db_script_string SET content_loc3 = 'Ich weiß, dass ihr da seid, Schufft. Verlasst mein Haus oder ihr lernt die anderen am Fuß des Weltenbaums kennen.' WHERE ( entry = 2000000196);
UPDATE db_script_string SET content_loc3 = 'Schmutz! Überall Schmutz! Der Wald muss gereinigt werden' WHERE ( entry = 2000000197);
UPDATE db_script_string SET content_loc3 = 'Lösung, kauf.' WHERE ( entry = 2000000221);
UPDATE db_script_string SET content_loc3 = 'Heisse Speisen!' WHERE ( entry = 2000000222);
UPDATE db_script_string SET content_loc3 = 'ICH WERDE NEHMEN ALLE LEBEN' WHERE ( entry = 2000000226);
UPDATE db_script_string SET content_loc3 = 'ICH FÜHLE DAS GEBRATENE FLEISCH' WHERE ( entry = 2000000227);
UPDATE db_script_string SET content_loc3 = 'ICH WERDE  EUCH ALLE ZERSTÖREN' WHERE ( entry = 2000000238);
UPDATE db_script_string SET content_loc3 = 'Ich hatte ein geheimes Treffen zwischen Kriegshäuptling Thrall und König Wrynn hier in Theramore arangiert.' WHERE ( entry = 2000001000);
UPDATE db_script_string SET content_loc3 = 'Der König sollte per Schiff anreisen, im Geheimen. Aber das Schiff kam nie an und König Wrynn verschwand.' WHERE ( entry = 2000001001);
UPDATE db_script_string SET content_loc3 = 'Eure Hilfe ermöglichte uns die Verbindung der Defias zum Kopf hinter der Entführung, Onyxia, zu ziehen, die sich als Mitglied des Königlichen Hofs ausgab' WHERE ( entry = 2000001002);
UPDATE db_script_string SET content_loc3 = 'Inzwischen hat es der König geschafft seinen Entführern zu entkommen und nach Sturmwind zurückzukehren, um die Angelegenheit mit Onyxia zu erledigen.' WHERE ( entry = 2000001003);
UPDATE db_script_string SET content_loc3 = 'Ich werde verbreiten, dass ihr die Verbindung zu den Defias entdeckt habt. Ich war ein Trottel als ich vermutete, dass sie nach dem Sieg über Edwin van Cleef zerbrochen seien und König Wrynn wird sicher für alle Verbliebenen ein Exempel stattuieren.' WHERE ( entry = 2000001004);
UPDATE db_script_string SET content_loc3 = 'Unter den Schädeln kein Yenniku, $N. Das erleichtert mich sehr.' WHERE ( entry = 2000001005);
UPDATE db_script_string SET content_loc3 = 'Was für eine Kraft durchströmt mich? Vielleicht ist es die Macht des Schamanen, mit dem ich über Tor''gan sprach?' WHERE ( entry = 2000001006);
UPDATE db_script_string SET content_loc3 = 'Unglaublich! Ich fühle mich wiedergeboren. Die Kraft kommt zu mir zurück!' WHERE ( entry = 2000001007);
UPDATE db_script_string SET content_loc3 = 'Ich kann natürlich eine Anleitung für die Mixtur finden …' WHERE ( entry = 2000001009);
UPDATE db_script_string SET content_loc3 = 'Ha! $N, Ich habe mich nicht von ihren Sitzen bewegt!' WHERE ( entry = 2000001010);
UPDATE db_script_string SET content_loc3 = 'versucht das Holzbei Maury zu öffnen …' WHERE ( entry = 2000001011);
UPDATE db_script_string SET content_loc3 = 'zu sehen auf dem Gedankenauge und den singenden Kristallen …' WHERE ( entry = 2000001012);
UPDATE db_script_string SET content_loc3 = 'Seelenedelstein Yenniku fertig, $N …' WHERE ( entry = 2000001013);
UPDATE db_script_string SET content_loc3 = 'Blau mit Rot ... Ich ahnte so etwas …' WHERE ( entry = 2000001015);
UPDATE db_script_string SET content_loc3 = 'Hier ist es, $N! Endlich verstehe ich!' WHERE ( entry = 2000001016);
UPDATE db_script_string SET content_loc3 = 'nervöser Blick.' WHERE ( entry = 2000001017);
UPDATE db_script_string SET content_loc3 = 'Seid ihr sicher, dass unser nicht verfolgt wird? Ich habe eine schlechte Vorahnung …' WHERE ( entry = 2000001018);
UPDATE db_script_string SET content_loc3 = 'Seid vorsichtig!' WHERE ( entry = 2000001019);
UPDATE db_script_string SET content_loc3 = 'Los!' WHERE ( entry = 2000001021);
UPDATE db_script_string SET content_loc3 = 'Information nach der sucht ihr … Ich kann nicht machen einfach so. Beweist, dass wir gemeinsamen Feind haben.' WHERE ( entry = 2000001024);
UPDATE db_script_string SET content_loc3 = 'Nein, nicht so. Was ist hier passiert?' WHERE ( entry = 2000001022);
UPDATE db_script_string SET content_loc3 = 'Das Metall hat seine Magie verloren. Ich könnte seine Waffe nachbauen, aber sie würde sich von einem herkömmlichen Schwert nicht unterscheiden.' WHERE ( entry = 2000001023);
UPDATE db_script_string SET content_loc3 = 'Denkt daran, $N, mit Blutsporen Pulver kann man alle Magnatauren in Gammutra schwächen.' WHERE ( entry = 2000001025);
UPDATE db_script_string SET content_loc3 = 'Geht auf jeden Fall ins Heiligtum und kommt durch den südlichen Pass. $N. Weisst du, leite sie am Kampf vorbei um sie vor der Gräul zu bewahren … halte sie fern.' WHERE ( entry = 2000001030);
UPDATE db_script_string SET content_loc3 = 'Gegeissselte Trooolle rössssten …' WHERE ( entry = 2000001031);
UPDATE db_script_string SET content_loc3 = '… aufm offenen Feuer …' WHERE ( entry = 2000001032);
UPDATE db_script_string SET content_loc3 = 'rülpst laut …' WHERE ( entry = 2000001033);
UPDATE db_script_string SET content_loc3 = 'Das ist es! So weit bin ich gekommen ... Was denkt ihr?' WHERE ( entry = 2000001034);
UPDATE db_script_string SET content_loc3 = 'Götter der Vergangenheit, wir bitten euch. Was sollen wir tun? Wie können wir die Götter des Landes schützen?' WHERE ( entry = 2000001035);
UPDATE db_script_string SET content_loc3 = 'Ausgezeichnetes Horn! Es würd schwer das beste zu wählen …' WHERE ( entry = 2000001036);
UPDATE db_script_string SET content_loc3 = 'Vielleicht nehm ich dieses Horn. Jetzt musst du es nur noch schön abschneiden! Vermutlich wird das nicht einfach. Weil ich nicht einmal weiß, wie man einen weiblichen Yeti fängt.' WHERE ( entry = 2000001037);
UPDATE db_script_string SET content_loc3 = 'Ich schneide das Horn, aber bevor es die traditionellenen Schnitzereien bekommt, propiert ob es geht. Helft ihr mir beim testen?' WHERE ( entry = 2000001038);
UPDATE db_script_string SET content_loc3 = 'Ausgezeichnet $N! Das ist etwas, das wir auf jeden Fall tun sollten! Und jetzt – für die Arbeit.' WHERE ( entry = 2000001039);
UPDATE db_script_string SET content_loc3 = 'Alles .. genug für heute!' WHERE ( entry = 2000001040);
UPDATE db_script_string SET content_loc3 = 'Denkt daran, $N, dass ist kein Sprint. Diese Prüfung des Jägers – ist ein Test der Ausdauer für lange Expeditionen.' WHERE ( entry = 2000001041);
UPDATE db_script_string SET content_loc3 = 'Wenn die positiv ausgerichteten Energien mit den negativen kollidieren,  negieren sie sich nicht gegenseitig.' WHERE ( entry = 2000005158);
UPDATE db_script_string SET content_loc3 = 'Aber würde das nicht bedeuten, dass man die Ströme kreuzen muss? Ist das nicht sehr schlecht?' WHERE ( entry = 2000005160);
UPDATE db_script_string SET content_loc3 = 'Aber würde das nicht bedeuten, dass man die Ströme kreuzen muss? Ist das nicht sehr schlecht?' WHERE ( entry = 2000005165);
UPDATE db_script_string SET content_loc3 = 'Die Geißel ist ein Schandfleck auf diesem makellosen Land. Bei der Macht meines Erschaffers, ich werde jeden einzelnen ihrer schwächlichen Knochen unter meinem Absatz zerquetschen.

Ich will die Geißel genauso stoppen wie ihr. Wie kann ich helfen?' WHERE ( entry = 2000000241);
UPDATE db_script_string SET content_loc3 = 'Die Titanen haben das Leben nicht über Nacht erschaffen. Der Prozess war schrittweise und benötigte eine große Menge an Versuchen und Wiederholungen.

Aus diesem Grund existieren so streng bewachte Orte wie das Sholazarbecken.

Um die Sicherheit ihrer Versuchsstellen zu garantieren, haben die Titanen einen Schutzmechanismus erschaffen. Seine zerstörerischen Kräfte sind jedoch unvergleichlich und ich nicht mehr sagen, bis ihr nicht eure Lehnstreue meiner Sache schwört.

Ihr könnt mir trauen. Ich bin kein Freund des Lichkönigs.' WHERE ( entry = 2000000242);
UPDATE db_script_string SET content_loc3 = 'Es grenzt an Frevel, dass diese Geheimnisse einem Sterblichen wie euch offenbart werden, aber ich habe kaum eine andere Wahl.

Schon seit Freya, Tochter der Titanen, mich hier gelassen hat habe ich nur eine einzige Aufgabe und darf nicht versagen. Das Leben muss unter allen Umständen geschützt werden.

Es gibt ein Wegtor, dass dieses Ort mit einem diesem sehr ähnlichen verbindet. Dort kann die Waffe, die wir suchen, gefunden werden.

Ich werde nicht versagen.' WHERE ( entry = 2000000243);
UPDATE db_script_string SET content_loc3 = 'Das ist alles falsch, $N. In den Geschichten die mir Wildzähmerin Barah erzählte, war Sturmhuf ein Held, nicht der Schurke.' WHERE ( entry = 2000001042);
UPDATE db_script_string SET content_loc3 = 'Nordwind – der alte Feind Taunka, Meister der Elemente und der selben Kraft die den alten Völkern das Leben ausgesaugt hat.' WHERE ( entry = 2000001043);
UPDATE db_script_string SET content_loc3 = 'Sie würden eher sterben, als sich vor dem Nordwind beugen. Da ist etwas falsch.' WHERE ( entry = 2000001044);
UPDATE db_script_string SET content_loc3 = 'Lehrenhammer …' WHERE ( entry = 2000001045);
UPDATE db_script_string SET content_loc3 = 'Das bestätigt unsere Vermutung. Die Zeitlinie wurde beschädigt und dreht sich im falschen Muster. Aber wie?' WHERE ( entry = 2000001046);
UPDATE db_script_string SET content_loc3 = 'Oh, diese kleben! Ich frag mich wie sie das Gewebe fest gemacht haben?' WHERE ( entry = 2000001047);
UPDATE db_script_string SET content_loc3 = 'ACK! Oh nein, Ich habe mich selbst verwebt! Es klebt. MEIN HAAR!' WHERE ( entry = 2000001048);
UPDATE db_script_string SET content_loc3 = 'Keine Angst mein Freund. Rokhan wird für alles sorgen. Es kann einfach nicht entkommen.' WHERE ( entry = 2000001049);
UPDATE db_script_string SET content_loc3 = 'Geister erhört uns! Fühlst du es, $N?' WHERE ( entry = 2000001050);
UPDATE db_script_string SET content_loc3 = 'Der Wald liegt auf der Westseite des Tausenwintersees. Sucht die geschmiedete Herzfigur. Kein Zweifel, sie werden sich über eure Ankunft freuen …' WHERE ( entry = 2000001051);
UPDATE db_script_string SET content_loc3 = 'Töte sie alle, $N!' WHERE ( entry = 2000001052);
UPDATE db_script_string SET content_loc3 = 'Und jetzt werde ich diesen leuchtenden Kristall füllen, damit wir all die Lügen und Betrügereien entlarven können und ' WHERE ( entry = 2000001053);
UPDATE db_script_string SET content_loc3 = 'Lasst uns die Wahrheit lernen. Wenn sich ein Mörder unter uns verbirgt, und weis die richtige Richtung für die Suche.' WHERE ( entry = 2000001054);
UPDATE db_script_string SET content_loc3 = 'hört auf den Bericht $N …' WHERE ( entry = 2000001055);
UPDATE db_script_string SET content_loc3 = 'Was?! Flammenschwert erweitert den Einflussbereich?! Wir müssen herausfinden was was ist!' WHERE ( entry = 2000001056);
UPDATE db_script_string SET content_loc3 = 'trifft die verdrehten Krallen.' WHERE ( entry = 2000000999);
UPDATE db_script_string SET content_loc3 = 'Eiswasserfälle im Osten, Bruder. Geht dorthin mit den besten Rüstungen die es gibt. Die Allianz versteht gar nicht wen sie da angegriffen hat.' WHERE ( entry = 2000001057);
UPDATE db_script_string SET content_loc3 = 'Hört, der Todesritter … folgt der Stimme seines Meisters! Er ruft dich!' WHERE ( entry = 2000001058);
UPDATE db_script_string SET content_loc3 = 'Krieger der Geißel, hört meinen Ruf! Dieser Tag wird dem Scharlachroten Orden den Tod bringen! Leert das Land! Lasst den Tod hier sesshaft werden!' WHERE ( entry = 2000001059);
UPDATE db_script_string SET content_loc3 = 'Stop …' WHERE ( entry = 2000001060);
UPDATE db_script_string SET content_loc3 = 'Es ist nur …' WHERE ( entry = 2000001061);
UPDATE db_script_string SET content_loc3 = 'Bier! Das übliche Bier!' WHERE ( entry = 2000001062);
UPDATE db_script_string SET content_loc3 = 'Da ist nichts ungewöhnlich.' WHERE ( entry = 2000001063);
UPDATE db_script_string SET content_loc3 = 'Hey, du! Versuch einfach die Bonen über Grick zu spucken! Verstanden?' WHERE ( entry = 2000001064);
UPDATE db_script_string SET content_loc3 = 'Sie verstauen die Werkzeuge hier in diesen Kisten. Sucht nach ihnen in der Nähe der Zelte.' WHERE ( entry = 2000001065);
UPDATE db_script_string SET content_loc3 = 'Ich habe nur die Runen ausgeschnitten, die euch gegen den Giganten helfen.' WHERE ( entry = 2000001066);
UPDATE db_script_string SET content_loc3 = 'Ich werde die Runen „Norden“ und „Westen“ nicht schneiden – wer weiß welchen Einfluss sie auf die Giganten haben. Hier .... fehlt nur noch das enthaltene Vlies, welches entscheidet, wie lange ihr die Kreatur kontrollieren könnt.' WHERE ( entry = 2000001067);
UPDATE db_script_string SET content_loc3 = 'Und hier ist die Runen Abhängigkeit … Ich hoffe ich habe sie richtig geschnitten. Sie wird natürlich nicht so tödlich sein wie die Runen der Eisenzwerge, aber immerhin kann es etwas' WHERE ( entry = 2000001068);
UPDATE db_script_string SET content_loc3 = 'Großer Gott, ihr habt den schwachsinnigen Joe getötet und habt das Fleisch mit euch genommen! Woher wusstet ihr wonach wir suchen?' WHERE ( entry = 2000001069);
UPDATE db_script_string SET content_loc3 = 'Nun, wenn ihr gekommen seid um mich zu töten, könntet ihr zumindest warten bis ich Griselda gefüttert habe? Das arme Mädchen hat seit Tagen nichts gegessen.' WHERE ( entry = 2000001070);
UPDATE db_script_string SET content_loc3 = 'Hier, Mädchen. Kannst du sie füttern bevor wir den schwachsinnigen Mörder Joe töten!' WHERE ( entry = 2000001071);
UPDATE db_script_string SET content_loc3 = 'Wie konntet ihr den armen Joe töten? Und warum habt ihr das Fleisch zurückgebracht?' WHERE ( entry = 2000001072);
UPDATE db_script_string SET content_loc3 = 'Du – ein Rätsel, ja, ein echtes Mysterium … Hier sind … Ich bin nicht sehr versessen auf Rätsel.' WHERE ( entry = 2000001073);
UPDATE db_script_string SET content_loc3 = 'Ihr geht besser weg, wenn Griselda euch nicht als Dessert haben soll …' WHERE ( entry = 2000001074);
UPDATE db_script_string SET content_loc3 = 'Die Einleitung der Rune „Omega“ ist vollständig. Aktivierung war erfolgreich.' WHERE ( entry = 2000001075);
UPDATE db_script_string SET content_loc3 = 'Fezzix, ich vermute, wir haben über dein kleines Problem mit dem Motor entschieden.' WHERE ( entry = 2000001076);
UPDATE db_script_string SET content_loc3 = 'Diese … dunkle … Energie! Wie ist das möglich?' WHERE ( entry = 2000001077);
UPDATE db_script_string SET content_loc3 = 'Dieses Buch würde mir unbegrenzte Macht über meine Feinde geben … ich wäre … unaufhaltsam!' WHERE ( entry = 2000001078);
UPDATE db_script_string SET content_loc3 = 'Nein, nehmt das, $N! Mein Wille ist bereits so geschwächt durch seine dunkle Macht. Nehmt es und tötet Varedis!' WHERE ( entry = 2000001079);
UPDATE db_script_string SET content_loc3 = 'Ich habe ein paar Kontrollpanele unterhalb des Hangs errichtet. Schnell borgt eins und übernehmt die Kontrolle eines Teufelshäschers! Ihr habt nur wenig Zeit.' WHERE ( entry = 2000001080);
UPDATE db_script_string SET content_loc3 = 'Einfacher als ich dachte … markiert Thoradin als intakt.' WHERE ( entry = 2000001081);
UPDATE db_script_string SET content_loc3 = 'beginnt den Zauberspruch über Herzen und Zungen zu lesen.' WHERE ( entry = 2000001082);
UPDATE db_script_string SET content_loc3 = 'Brut von Onyxia!' WHERE ( entry = 2000001083);
UPDATE db_script_string SET content_loc3 = 'Ich glaub Ich hab gehört, dass er schon in Arbeit ist.' WHERE ( entry = 2000001084);
UPDATE db_script_string SET content_loc3 = 'Grüßt $N, $Gden neuen Ogerkönig:die neue Ogerkönigin!!!' WHERE ( entry = 2000001085);
UPDATE db_script_string SET content_loc3 = 'Meine Dankbarkeit kennt keine Grenzen, $N. Endlich konnte ich den Turm verlassen und bin von den Fesseln des schlechten Magiers Kael befreit!' WHERE ( entry = 2000001086);
UPDATE db_script_string SET content_loc3 = 'Nein! Wie das Ritual konnte gebrochen?' WHERE ( entry = 2000001087);
UPDATE db_script_string SET content_loc3 = 'Verflucht die Flüchtenden! Sie müssen sich einen anderen Weg suchen.' WHERE ( entry = 2000001088);
UPDATE db_script_string SET content_loc3 = 'Ja bejubelt $N! $Ger:Sie hat die Stadt vor der Brennenden Legion gerettet!' WHERE ( entry = 2000001089);
UPDATE db_script_string SET content_loc3 = 'Hurra!' WHERE ( entry = 2000001090);
UPDATE db_script_string SET content_loc3 = 'Sprecht mit Schwadronskommandant Brack, $N. Er wird euch mit einem unserer gepanzerten Flügeldrachenzerstörer ausstatten. Und, viel Glück! ' WHERE ( entry = 2000000018);
UPDATE db_script_string SET content_loc3 = 'Menschen von Sturmwind! Bürger der Allianz! Hört auf euren König!' WHERE ( entry = 2000001091);
UPDATE db_script_string SET content_loc3 = 'Heute ist der erste von vielen Siegen gegen die Geißel! Todesritter, die einst dem Lichkönig dienten, brachen aus seinem teuflischen Griff aus und formten eine neue Allianz, um seiner Tyrannei zu wiederstehen.' WHERE ( entry = 2000001092);
UPDATE db_script_string SET content_loc3 = 'Ihr sollt sie herzlich willkommen heißen die vergangen Helden der Allianz und ihnen mit dem Respekt begegnen, den ihr allen Alliierten Sturmwinds entgegenbringt!' WHERE ( entry = 2000001093);
UPDATE db_script_string SET content_loc3 = 'Ruhm der Allianz!' WHERE ( entry = 2000001094);
UPDATE db_script_string SET content_loc3 = 'Willkommen in der Ehrenfeste, $N. Es ist gut, dass ihr bei uns seid!' WHERE ( entry = 2000001095);
UPDATE db_script_string SET content_loc3 = 'betrachtet den Talisman den $N ihm gab.' WHERE ( entry = 2000001096);
UPDATE db_script_string SET content_loc3 = 'Ah … Soldat Wache. Er war der fröhlichere … noch nicht den Hals verloren während eines Angriffs auf das Blutende Auge …' WHERE ( entry = 2000001097);
UPDATE db_script_string SET content_loc3 = 'seht die Festung des Blutenden Auges Zet''gor …' WHERE ( entry = 2000001098);
UPDATE db_script_string SET content_loc3 = 'Verdammt seid ihr abscheulichen Höllenorcs! Lasst euren Geist das Böse aufsaugen, dem ihr huldigt!' WHERE ( entry = 2000001099);
UPDATE db_script_string SET content_loc3 = 'Freiheit! Endlich! Meine Leute werden wieder den Wind und seine Stimme kennen lernen. Ich danke euch, Fremder.' WHERE ( entry = 2000001200);
UPDATE db_script_string SET content_loc3 = 'Ich bin frei! Geister des Wassers helft meinen Leuten. Es wird uns die nötige Weisheit bringen die nötig ist um in diesem rauen Land zu überleben. Ich stehe in eurer Schuld, $N.' WHERE ( entry = 2000001201);
UPDATE db_script_string SET content_loc3 = 'Ich bin frei! Ich frage die Geister des Feuers uns zu helfen, so das meine Leute den Mut gefunden haben mit den Besitzern zu kämpfen! Ich danke euch, $R.' WHERE ( entry = 2000001202);
UPDATE db_script_string SET content_loc3 = 'Bah! So ekelhaft! Ja, ich würde sie rammen, das ist nicht groß!' WHERE ( entry = 2000001203);
UPDATE db_script_string SET content_loc3 = 'Gut das ich es geschafft habe Kopien der Gasmasken der Teufelsbrut anzufertigen …' WHERE ( entry = 2000001204);
UPDATE db_script_string SET content_loc3 = 'Ok, $N, fang an. Finger gekreuzt Arme, Beine, Augen und was du da hast kannst du noch kreuzen! …' WHERE ( entry = 2000001209);
UPDATE db_script_string SET content_loc3 = 'Oh, nein … es funktioniert nicht! Irgendwie Ich fühl mich … erleichtert.' WHERE ( entry = 2000001210);
UPDATE db_script_string SET content_loc3 = 'Ausgezeichnet, $N, hier ist sie: Verkleidet als Orc des Kriegshymnenklan, mit der Kraft der Illusion und ergänzt durch eine Vorahnung.' WHERE ( entry = 2000001211);
UPDATE db_script_string SET content_loc3 = 'Mit der Rückkehr wartet die Welt auf die Antwort!' WHERE ( entry = 2000001212);
UPDATE db_script_string SET content_loc3 = 'Geht nicht zu weit den Gang runter, $N. Bleibt beim Hauptmann uns seinen Männern … ihr müsst alles töten.' WHERE ( entry = 2000001213);
UPDATE db_script_string SET content_loc3 = 'Ausgezeichnet. Derweil ihr nicht alles alles zermalmt und zerstört, was auf seinem Weg ist, werden sie den Unterschied nicht merken.' WHERE ( entry = 2000001214);
UPDATE db_script_string SET content_loc3 = 'Er will das ich WAS tue?' WHERE ( entry = 2000001215);
UPDATE db_script_string SET content_loc3 = 'Nun, er wird nicht zäh werden durch den Trank, wenn er wirklich will, dass meine Leute ihre Studien aufgeben und stattdessen für das Militär arbeiten sollen!' WHERE ( entry = 2000001216);
UPDATE db_script_string SET content_loc3 = 'liest den letzten Eintrag in Branns Protokoll.' WHERE ( entry = 2000001217);
UPDATE db_script_string SET content_loc3 = 'Unglaublich! Hier steht das Brann eine mysteriöse Tafel, bedeckt mit Runen, in den Tiefen von Thor Modan entdeckte!' WHERE ( entry = 2000001218);
UPDATE db_script_string SET content_loc3 = 'Brann scheibt, dass er an einer Entschlüsselung dieser Runen Schriftzeichen arbeitete, als sie von Riesen angegriffen wurden.' WHERE ( entry = 2000001219);
UPDATE db_script_string SET content_loc3 = 'Er entschlüsselte laut die Innschrifft einer Platte, aber es scheint, dass er die Übersetzung aufschrieb.' WHERE ( entry = 2000001220);
UPDATE db_script_string SET content_loc3 = 'Beim Barte von Magni, wir müssen den Schlüssel wiederherstellen, der uns ermöglicht die in Stein gemeiselten Worte zu lesen. Wir könnten ihm eng auf den Fersen sein!' WHERE ( entry = 2000001221);
UPDATE db_script_string SET content_loc3 = 'Endlich haben wir die Teile den Geist von Gnomeregan zu reparieren.' WHERE ( entry = 2000001222);
UPDATE db_script_string SET content_loc3 = 'Jetzt noch ein paar Verbesserungen hier, eine kleine Abstimmung da …' WHERE ( entry = 2000001223);
UPDATE db_script_string SET content_loc3 = 'Und du – Geist von Gnomeregan!' WHERE ( entry = 2000001224);
UPDATE db_script_string SET content_loc3 = 'Du kannst es benutzen, aber beschwer dich nicht: nach der Reparatur der Sitze kann ein Sägezahn oder so etwas kleben. Was ich hatte – habe ich alles verarbeitet.' WHERE ( entry = 2000001225);
UPDATE db_script_string SET content_loc3 = 'Es sind schon wieder diese verdammten Eisenzwerge! Irgendwie haben sie ihn vor uns gefunden.' WHERE ( entry = 2000001227);
UPDATE db_script_string SET content_loc3 = 'Sie werden nicht aufgeben, bis sie ihn gefunden haben. Wir können das nicht zulassen $N und Brann weiß das.' WHERE ( entry = 2000001228);
UPDATE db_script_string SET content_loc3 = 'Hier sind ein paar kryptische Anleitungen in dieser Notiz. Brann muss einen Fluchtplan gehabt haben, aber er konnte der Ergreifung nicht für immer entgehen …' WHERE ( entry = 2000001229);
UPDATE db_script_string SET content_loc3 = 'Jetzt liegts an dir ihn vor den Einsenzwergen zu finden!' WHERE ( entry = 2000001230);
UPDATE db_script_string SET content_loc3 = 'Hey, danke.' WHERE ( entry = 2000001231);
UPDATE db_script_string SET content_loc3 = '%s liest den Zettel.' WHERE ( entry = 2000001232);
UPDATE db_script_string SET content_loc3 = '… erhaltet 50 Prozent auf die Kleidung der Deserteure? Was ist das für ein Müll?' WHERE ( entry = 2000001233);
UPDATE db_script_string SET content_loc3 = 'Was eine verrückte Menge! Glaubt ihr diesen Unsinn etwa?' WHERE ( entry = 2000001234);
UPDATE db_script_string SET content_loc3 = 'Schaut euch um, $N. Vielleicht seht ihr etwas, dass ich übersehen habe.' WHERE ( entry = 2000001235);
UPDATE db_script_string SET content_loc3 = '%s zeigt auf einen Stapel Bücher …' WHERE ( entry = 2000001236);
UPDATE db_script_string SET content_loc3 = 'Ein Steinwall konnte gerettet werden! Ein dreifaches Hurra für $N!' WHERE ( entry = 2000001237);
UPDATE db_script_string SET content_loc3 = '%s hört sich $Ns bitte an.' WHERE ( entry = 2000000270);
UPDATE db_script_string SET content_loc3 = 'Du tatest gut daran zu kommen. Meine Weisheit soll dein sein.' WHERE ( entry = 2000000271);
UPDATE db_script_string SET content_loc3 = '%s erstellt sein Gift …' WHERE ( entry = 2000000272);
UPDATE db_script_string SET content_loc3 = 'Da bist du $N. Das Gift ist fertig.' WHERE ( entry = 2000000273);
UPDATE db_script_string SET content_loc3 = '%s füllt einen Behälter mit dem Gift.' WHERE ( entry = 2000000274);
UPDATE db_script_string SET content_loc3 = 'Das Gift ist fertig, $N.' WHERE ( entry = 2000000275);
UPDATE db_script_string SET content_loc3 = '$N, pass auf, bitte, Schlangenstrunkranke, die ich aus der Höhle mitgebracht habe, also weißt du worauf du aufpassen musst …' WHERE ( entry = 2000001238);
UPDATE db_script_string SET content_loc3 = 'Es dauert nur ein paar Minuten das Serum zuzubereiten, $N.' WHERE ( entry = 2000000289);
UPDATE db_script_string SET content_loc3 = 'Fast fertig …' WHERE ( entry = 2000000290);
UPDATE db_script_string SET content_loc3 = 'Endlich ist das Serum fertig, $N. Jetzt kommt her. Wir müssen reden.' WHERE ( entry = 2000000291);

SET NAMES 'latin1';