UPDATE creature_ai_texts SET content_loc3='Es ist nicht klug, mich wütend zu machen.' WHERE entry=-73;
UPDATE creature_ai_texts SET content_loc3='Völlig unwirksam. Genauso wie ich jemand anderes kenne.' WHERE entry=-74;
UPDATE creature_ai_texts SET content_loc3='Ihr habt euch den falschen Gegner ausgesucht.' WHERE entry=-75;
UPDATE creature_ai_texts SET content_loc3='Was tut Ihr? Diese Muster sind tadellos!' WHERE entry=-17;
UPDATE creature_ai_texts SET content_loc3='Die Natur beugt sich meinem Willen.' WHERE entry=-18;
UPDATE creature_ai_texts SET content_loc3='Endorel aluminor!' WHERE entry=-19;
UPDATE creature_ai_texts SET content_loc3='Euer Leben ist nun zu Ende.' WHERE entry=-20;
UPDATE creature_ai_texts SET content_loc3='Diese Muster... müssen ... bewahrt werden' WHERE entry=-21;
UPDATE creature_ai_texts SET content_loc3='Nun bin ich wirklich wütend.' WHERE entry=-76;
UPDATE creature_ai_texts SET content_loc3='Ahh...Das ist viel besser.' WHERE entry=-77;
UPDATE creature_ai_texts SET content_loc3='Ahh... genau, was ich brauchte.' WHERE entry=-78;
UPDATE creature_ai_texts SET content_loc3='Erntet den Sturm!' WHERE entry=-79;
UPDATE creature_ai_texts SET content_loc3='Ich schneide euch in Stücke!' WHERE entry=-80;
UPDATE creature_ai_texts SET content_loc3='Ich bin der Jäger! Ihr seid die Beute...' WHERE entry=-133;
UPDATE creature_ai_texts SET content_loc3='Ihr könnt... meinen... Geist... nicht töten!' WHERE entry=-134;
UPDATE creature_ai_texts SET content_loc3='Labt euch, meine Brüda!' WHERE entry=-135;
UPDATE creature_ai_texts SET content_loc3='Hört mit eurem Weinen auf!' WHERE entry=-136;
UPDATE creature_ai_texts SET content_loc3='Ihr habt nichts erreicht!' WHERE entry=-137;
UPDATE creature_ai_texts SET content_loc3='Ihr stehlt mir nur meine Zeit Man!' WHERE entry=-138;
UPDATE creature_ai_texts SET content_loc3='Kommt helft mir, Bruda!' WHERE entry=-139;
UPDATE creature_ai_texts SET content_loc3='Anchoret Nindumen, ich muss Euch um etwas bitten.' WHERE entry=-274;
UPDATE creature_ai_texts SET content_loc3='Wir haben gerade eine weitere unerfahrene Truppe nach Nagrand geschickt. Wollt Ihr für sie beten?' WHERE entry=-275;
UPDATE creature_ai_texts SET content_loc3='So soll es sein.' WHERE entry=-276;
UPDATE creature_ai_texts SET content_loc3='Dies ist das Reich der Geißel. Nur den Toten wird Einlass gewährt!' WHERE entry=-634;
UPDATE creature_ai_texts SET content_loc3='Sie hungern...' WHERE entry=-635;
UPDATE creature_ai_texts SET content_loc3='Essenszeit, meine Kleinen!' WHERE entry=-636;
UPDATE creature_ai_texts SET content_loc3='Wie Anub\'arak befiehlt!' WHERE entry=-637;
UPDATE creature_ai_texts SET content_loc3='Hash\'tak hi\'tak.' WHERE entry=-638;
UPDATE creature_ai_texts SET content_loc3='Es war töricht her zu kommen.' WHERE entry=-639;
UPDATE creature_ai_texts SET content_loc3='Habt ein Auge auf den Tunnel... wir dürfen keinen durchlassen!' WHERE entry=-640;
UPDATE creature_ai_texts SET content_loc3='Ich höre Schritte. Seid wachsam.' WHERE entry=-641;
UPDATE creature_ai_texts SET content_loc3='Ich spüre Lebende. Seid bereit' WHERE entry=-642;
UPDATE creature_ai_texts SET content_loc3='Ich sollte dankbar sein... doch das kann ich schon lange nicht mehr...' WHERE entry=-643;
UPDATE creature_ai_texts SET content_loc3='Ewige Pein erwartet Euch!' WHERE entry=-644;
UPDATE creature_ai_texts SET content_loc3='Eure Rüstung hilft nicht gegen meine Heuschrecken!' WHERE entry=-645;
UPDATE creature_ai_texts SET content_loc3='Uunak-hissss tik-k-k-k-k!' WHERE entry=-646;
UPDATE creature_ai_texts SET content_loc3='Die Seuche komme über Euch!' WHERE entry=-647;
UPDATE creature_ai_texts SET content_loc3='Ihr sollt meiner Folter aus erster Hand spüren!' WHERE entry=-648;
UPDATE creature_ai_texts SET content_loc3='Ihr habt Eure Wahl getroffen.' WHERE entry=-649;
UPDATE creature_ai_texts SET content_loc3='Schon bald wird der Meister nach Euch rufen.' WHERE entry=-650;
UPDATE creature_ai_texts SET content_loc3='Auum na-l ak-k-k-k, isshhh.' WHERE entry=-651;
UPDATE creature_ai_texts SET content_loc3='Kommt, meine Brüder! Stürzt Euch auf Ihr Fleisch!' WHERE entry=-652;
UPDATE creature_ai_texts SET content_loc3='Tharon\'ja sieht alles! Sterbliche werden der ewigen Dynastie niemals ein Ende bereiten!' WHERE entry=-688;
UPDATE creature_ai_texts SET content_loc3='Un...unmöglich! Tharon\'ja währt ewig! Tharon\'ja... ist...' WHERE entry=-689;
UPDATE creature_ai_texts SET content_loc3='Wie es Tharon\'ja prophezeit hat!' WHERE entry=-690;
UPDATE creature_ai_texts SET content_loc3='Wie es geschrieben steht.' WHERE entry=-691;
UPDATE creature_ai_texts SET content_loc3='Euer Fleisch dient jetzt Tharon\'ja!' WHERE entry=-692;
UPDATE creature_ai_texts SET content_loc3='Tharon\'ja kann Eure sterbliche Hülle gebrauchen!' WHERE entry=-693;
UPDATE creature_ai_texts SET content_loc3='Nein! Ein Hauch... allzu kurz!' WHERE entry=-694;
UPDATE creature_ai_texts SET content_loc3='Argh!!! Tharon\'ja holt sich noch mehr!' WHERE entry=-695;
UPDATE creature_ai_texts SET content_loc3='Wir haben die Geißel zurückgeschlagen. Welche Chnace, meint Ihr, werdet IHR haben?' WHERE entry=-698;
UPDATE creature_ai_texts SET content_loc3='Macht Euch gefasst... auf was VIEL GRÖSSERES!' WHERE entry=-699;
UPDATE creature_ai_texts SET content_loc3='Der Boden wird Euch verschluck\'n!' WHERE entry=-700;
UPDATE creature_ai_texts SET content_loc3='Ich zerquetsch Euch, Kakerlaken!' WHERE entry=-701;
UPDATE creature_ai_texts SET content_loc3='Wer wird mich aufhalten, Ihr?' WHERE entry=-702;
UPDATE creature_ai_texts SET content_loc3='Jetzt seid Ihr nicht mehr so hart, was?' WHERE entry=-703;
UPDATE creature_ai_texts SET content_loc3='Wenn unsere Götter sterb\'n können... dann können wir das auch...' WHERE entry=-704;

/* creature_ai_texts entry=-705' translation is missing */

UPDATE creature_ai_texts SET content_loc3='%s beginnt, sich zu verwandeln!' WHERE entry=-706;
UPDATE creature_ai_texts SET content_loc3='%s verwandelt sich in ein Mammut!' WHERE entry=-707;
UPDATE creature_ai_texts SET content_loc3='Mehr Tod, mehr Blut, mehr Mampf!' WHERE entry=-708;
UPDATE creature_ai_texts SET content_loc3='So Hunger! Muss fressen!' WHERE entry=-709;
UPDATE creature_ai_texts SET content_loc3='Aaaargh...' WHERE entry=-710;
UPDATE creature_ai_texts SET content_loc3='Leiche macht Bumm!' WHERE entry=-711;
UPDATE creature_ai_texts SET content_loc3='Ich dich quetschen und fressen!' WHERE entry=-712;
UPDATE creature_ai_texts SET content_loc3='Kroshius leben? Kroshius zermalmen!' WHERE entry=-797;